import React from 'react'
import PropTypes from 'prop-types'
import Helmet from 'react-helmet'

// generated by https://metatags.io/
const TmHead = ({
  title,
  description,
  imageUrl,
  keywords,
  websiteUrl
}) =>
  <Helmet htmlAttributes={{ lang: 'sk' }}>
    <title>{title}</title>
    <meta name="title" content={title} />
    <meta name="description" content={description} />
    <meta name="keywords" content={keywords} />

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

    <meta property="og:type" content="website" />
    <meta property="og:url" content={websiteUrl} />
    <meta property="og:title" content={title} />
    <meta property="og:description" content={description} />
    <meta property="og:image" content={imageUrl} />

    <meta property="twitter:card" content="summary_large_image" />
    <meta property="twitter:url" content={websiteUrl} />
    <meta property="twitter:title" content={title} />
    <meta property="twitter:description" content={description} />
    <meta property="twitter:image" content={imageUrl} />
  </Helmet>

TmHead.propTypes = {
  title: PropTypes.string,
  description: PropTypes.string,
  keywords: PropTypes.string,
  websiteUrl: PropTypes.string,
  imageUrl: PropTypes.string
}

export default TmHead
