import React from 'react'
import PropTypes from 'prop-types'
import Helmet from 'react-helmet'

// generated by https://metatags.io/
const TmHead = ({
  title,
  description,
  imageUrl
}) =>
  <Helmet>
    <title>{title}</title>
    <meta name="title" content={title} />
    <meta name="description" content={description} />

    <meta property="og:type" content="website" />
    <meta property="og:url" content={location.origin} />
    <meta property="og:title" content={title} />
    <meta property="og:description" content={description} />
    <meta property="og:image" content={imageUrl} />

    <meta property="twitter:card" content="summary_large_image" />
    <meta property="twitter:url" content={location.origin} />
    <meta property="twitter:title" content={title} />
    <meta property="twitter:description" content={description} />
    <meta property="twitter:image" content={imageUrl} />
  </Helmet>

TmHead.propTypes = {
  title: PropTypes.string,
  description: PropTypes.string,
  imageUrl: PropTypes.string
}

export default TmHead
